# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1faHXd1tqPhRdA3e7gObc9T1CiPA4cSEV
"""

import scipy.stats
data=[1.17,0.99,1.1,1.08,1.11]
print (scipy.stats.ttest_1samp(data,1.0))

"""The mean value is 1.09. This assay is inaccurate because the p value is approximately 0.03668 which is less than the critical value of 0.05, thus the difference from the known concentration is significant."""

l1=[4.24, 4.39, 4.33, 4.28, 4.23, 4.41, 4.23, 4.13, 4.25, 4.26]
l2=[4.37, 4.38, 4.34, 4.45, 4.36, 4.4, 4.35, 4.47, 4.39, 4.44]
print (scipy.stats.ttest_ind(l1,l2,equal_var=False))

"""The mean value of [11] = 4.275 and the mean value of [12] = 4.395 so the difference in the mean values is 0.12. The two-sample t-test ( t18=−4.03756
 ,  P=0.001225
 ) shows this difference is statistically significant meaning that the new assay does not agree with the original and is not accurate.
"""

Before=[ 0.78, 0.41, 1.18, 0.8, 0.88]
After=[1.16, 0.5, 1.44, 1.15, 1.2]
print (scipy.stats.ttest_rel(Before,After))

"""The difference between the reaction times obtained was significant ( t9=-5.43920,  P=0.0055
 ), meaning that there is evidence drinking affects reaction time.
"""

group1 = [0.78, 0.41, 1.18, 0.8, 0.88]
group2 = [1.16, 0.5, 1.44, 1.15, 1.2]
# Using ttest_ind for a two-sample t-test
print(scipy.stats.ttest_ind(group1, group2, equal_var=False))

"""If you incorrectly used a two sample t-test, which would be incorrect because the data is paired, you would get P= 0.1996 which is greater than 0.05 so the result would not be significant. Hence, it is important to use the correct t-test."""

lv1=[1.52,1.54,1.72,1.75,1.89,2.13]
ls1=[5.,6.,7.,8.,9.,10.]
import matplotlib.pyplot as plt
plt.plot(ls1,lv1,'bo')
plt.xlabel('1/[S]')
_=plt.ylabel('$1/v_0$')

from sklearn import linear_model as lm
model=lm.LinearRegression()
ls1v=[[x] for x in ls1]
res=model.fit(ls1v,lv1)
print ('b = %g, a = %g' %(model.intercept_,model.coef_))
ylin=model.predict(ls1v)
plt.plot(ls1,lv1,'bo')
plt.plot(ls1,ylin,'r')
plt.xlabel('1/[S]')
_=plt.ylabel('$1/v_0$')

lv0=[0.0027,0.0034,0.0077,0.013,0.02]
lT=[300,310,320,330,340]
plt.plot(lT,lv0,'bo')
plt.xlabel('T')
_=plt.ylabel('$v_0$')

speeds=[0.0027,0.0034,0.0077,0.013,0.02]
import math
for s in speeds:
  print (math.log(s))

logv0=[-5.914503505971854,
-5.683979847360021,
-4.866534950122499,
-4.3428059215206005,
-3.912023005428146]
lT=[300,310,320,330,340]
plt.plot(lT,logv0,'bo')
plt.xlabel('T')
_=plt.ylabel('log$v_0$')

"""After I took the log of the speed, the relationship between the rate of enzyme activity and T was approximately linear. We can therefore suggest that there is an exponential increase of V0 with temperature over this range."""

from sklearn import linear_model as lm
import matplotlib.pyplot as plt

model = lm.LinearRegression()
lTv = [[x] for x in lT]
model.fit(lTv, logv0)

print('b (intercept) = %g, a (slope) = %g' % (model.intercept_, model.coef_[0]))

ylin = model.predict(lTv)

plt.plot(lT, logv0, 'bo', label='Data')
plt.plot(lT, ylin, 'r', label='Linear Fit')
plt.xlabel('T')
plt.ylabel('log $v_0$')
plt.legend()
plt.show()

"""From the Lineweaver-Burk fit, the intercept b corresponds to 1/Vmax and the slope a corresponds to Km/Vmax. Therefore, Vmax = 1/b and Km = a/b"""